[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.115.6",
    "kubernetes>=31.0.0",
    "llm-sandbox>=0.1.8",
    "pydantic>=2.10.5",
    "uvicorn>=0.34.0",
]
